version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: saas-template-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saas_template
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./apps/backend/src/database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d saas_template"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: saas-template-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
      target: development
    container_name: saas-template-backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: saas_template
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: your-development-jwt-secret
      AWS_REGION: us-east-1
      COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID:-your-cognito-user-pool-id}
      COGNITO_CLIENT_ID: ${COGNITO_CLIENT_ID:-your-cognito-client-id}
      CORS_ORIGIN: http://localhost:3001
    volumes:
      - ./apps/backend:/app/apps/backend
      - ./packages:/app/packages
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - /app/node_modules
      - /app/packages/shared/node_modules
    ports:
      - "3000:3000"

  admin-dashboard:
    build:
      context: .
      dockerfile: ./apps/admin-dashboard/Dockerfile
      target: development
    container_name: saas-template-admin
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3000
      NEXT_PUBLIC_AWS_REGION: us-east-1
      NEXT_PUBLIC_AWS_USER_POOL_ID: ${COGNITO_USER_POOL_ID:-your-cognito-user-pool-id}
      NEXT_PUBLIC_AWS_CLIENT_ID: ${COGNITO_CLIENT_ID:-your-cognito-client-id}
    volumes:
      - ./apps/admin-dashboard:/app/apps/admin-dashboard
      - ./packages:/app/packages
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - /app/node_modules
      - /app/packages/shared/node_modules
      - /app/apps/admin-dashboard/.next
    ports:
      - "3001:3000"

volumes:
  postgres_data:
  redis_data: