# This file contains template for Kubernetes secrets
# DO NOT commit actual secret values to version control
# Use kubectl create secret or external secret management tools

apiVersion: v1
kind: Secret
metadata:
  name: saas-secrets
  namespace: saas-template
type: Opaque
data:
  # Base64 encoded values - replace with actual encoded secrets
  db-host: <base64-encoded-db-host>
  db-username: <base64-encoded-db-username>
  db-password: <base64-encoded-db-password>
  db-database: <base64-encoded-db-database>
  redis-host: <base64-encoded-redis-host>
  redis-password: <base64-encoded-redis-password>
  jwt-secret: <base64-encoded-jwt-secret>
  cognito-user-pool-id: <base64-encoded-user-pool-id>
  cognito-client-id: <base64-encoded-client-id>
  cognito-client-secret: <base64-encoded-client-secret>
  nextauth-secret: <base64-encoded-nextauth-secret>

---
# GitHub Container Registry secret for pulling images
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: saas-template
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64-encoded-docker-config>

---
# Example of creating secrets with kubectl:
# kubectl create secret generic saas-secrets \
#   --from-literal=db-host="your-db-host" \
#   --from-literal=db-username="your-db-user" \
#   --from-literal=db-password="your-db-password" \
#   --from-literal=db-database="your-db-name" \
#   --from-literal=redis-host="your-redis-host" \
#   --from-literal=redis-password="your-redis-password" \
#   --from-literal=jwt-secret="your-jwt-secret" \
#   --from-literal=cognito-user-pool-id="your-pool-id" \
#   --from-literal=cognito-client-id="your-client-id" \
#   --from-literal=cognito-client-secret="your-client-secret" \
#   --from-literal=nextauth-secret="your-nextauth-secret" \
#   --namespace=saas-template

# kubectl create secret docker-registry ghcr-secret \
#   --docker-server=ghcr.io \
#   --docker-username=your-github-username \
#   --docker-password=your-github-token \
#   --namespace=saas-template