#!/bin/bash

echo "==========================================="
echo "AWS Cognito Development Environment Values"
echo "==========================================="
echo ""
echo "User Pool ID: $(terraform output -raw user_pool_id)"
echo "Backend Client ID: $(terraform output -raw backend_client_id)"
echo "Backend Client Secret: $(terraform output -raw backend_client_secret)"
echo "Frontend Client ID: $(terraform output -raw frontend_client_id)"
echo ""
echo "==========================================="
echo "Admin User Credentials"
echo "==========================================="
echo ""
echo "Email: admin@example.com"
echo "Temporary Password: TempPass123!"
echo ""
echo "NOTE: The admin user must change their password on first login."
echo "You can do this through the AWS Cognito console or implement a change password flow."
echo ""
echo "==========================================="
echo "Environment Files Updated"
echo "==========================================="
echo ""
echo "✓ /.env"
echo "✓ /apps/backend/.env.dev"
echo "✓ /apps/admin-dashboard/.env.local"
echo ""
echo "The containers have been restarted with the new configuration."
echo ""